canonical_host: lds.li
modules:
  oauth2ext:
    path: lds.li/oauth2ext
    git_url: https://github.com/lstoll/oauth2ext
  web:
    path: lds.li/web
    git_url: https://github.com/lstoll/web
  tinkrotate:
    path: lds.li/tinkrotate
    git_url: https://github.com/lstoll/tinkrotate
  oidccli:
    path: lds.li/oidccli
    git_url: https://github.com/lstoll/oidccli
    redirect_to: https://github.com/lstoll/oidccli
  passidp:
    path: lds.li/passidp
    git_url: https://github.com/lstoll/passidp
    redirect_to: https://github.com/lstoll/passidp
webfinger:
  "%%EMAIL%%":
    - rel: http://openid.net/specs/connect/1.0/issuer
      href: https://id.lds.li
